# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_path', models.CharField(blank=True, default=b'sirloin.png', max_length=100)),
                ('description', models.CharField(blank=True, default=b'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eget mollis urna, imperdiet malesuada eros. Nunc eget mollis urna, imperdiet malesuada eros.', max_length=2000)),
            ],
        ),
    ]
