# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysofra', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
