# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysofra', '0004_delete_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mysofraMail',
            new_name='Mail',
        ),
    ]
