# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysofra', '0005_auto_20170516_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_from',
            field=models.CharField(default=b'checkout@mysofra.at', max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_to',
            field=models.CharField(default=b'order@mysofra.at', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysofra.Category'),
        ),
    ]
